
//auth
export const AUTH = 'AUTH'
export const LOGOUT = 'LOGOUT'
export const FORGET_AND_RESET = 'FORGET_AND_RESET'

export const UPDATE_D_NAME = 'UPDATE_D_NAME'
export const UPDATE_D_QUESTION = 'UPDATE_D_QUESTION'
export const UPDATE_D_PASSWORD = 'UPDATE_D_PASSWORD'


//patients
export const FETCH_ALL = 'FETCH_ALL'
export const FETCH_PATIENT = 'FETCH_PATIENT'
export const FETCH_BY_SEARCH = 'FETCH_BY_SEARCH'
export const FETCH_STATISTIC = 'FETCH_STATISTIC'
export const DATE = 'DATE'

export const CREATE_P = 'CREATE_P'
export const UPDATE_P = 'UPDATE_P'
export const DELETE_P = 'DELETE_P'

// to use localstorage
export const FETCH_TO_UPDATE_PATIENT = 'FETCH_TO_UPDATE_PATIENT'
export const END_PATIENT_TO_UPDATE = 'END_PATIENT_TO_UPDATE'

export const FETCH_TO_ADD_CHECKUP = 'FETCH_TO_ADD_CHECKUP'
export const END_ADD_CHECKUP = 'END_ADD_CHECKUP'

export const FETCH_TO_ADD_TREATMENT = 'FETCH_TO_ADD_TREATMENT'
export const END_ADD_TREATMENT = 'END_ADD_TREATMENT'

export const FETCH_TO_ADD_MEDICAL_FOLDER = 'FETCH_TO_ADD_MEDICAL_FOLDER'
export const END_ADD_MEDICAL_FOLDER = 'END_ADD_MEDICAL_FOLDER'

// check-ups
export const FETCH_ALL_CHECKUPS = 'FETCH_ALL_CHECKUPS'
export const FETCH_CHECKUP = 'FETCH_CHECKUP'

export const CREATE_C = 'CREATE_C'
export const UPDATE_C = 'UPDATE_C'
export const DELETE_C = 'DELETE_C'

export const CHECKUP_TO_PRINT = 'CHECKUP_TO_PRINT'

// treatments
export const FETCH_ALL_TREATMENTS = 'FETCH_ALL_TREATMENTS'
export const FETCH_TREATMENT = 'FETCH_TREATMENT'

export const CREATE_T = 'CREATE_T'
export const UPDATE_T = 'UPDATE_T'
export const DELETE_T = 'DELETE_T'

export const TREATMENT_TO_PRINT = 'TREATMENT_TO_PRINT'

// medical folder
export const FETCH_PATIENT_MEDICAL_FOLDERS = 'FETCH_PATIENT_MEDICAL_FOLDERS'
export const FETCH_PATIENT_SINGLE_FOLDER = 'FETCH_PATIENT_SINGLE_FOLDER'

export const CREATE_MF ='CREATE_NF'
export const UPDATE_MF ='UPDATE_MF'
export const DELETE_MF ='DELETE_MF'

export const MEDICAL_FOLDER_TO_PRINT = 'MEDICAL_FOLDER_TO_PRINT'

export const MEDICAL_FOLDER_TO_UPDATE = 'MEDICAL_FOLDER_TO_UPDATE'

//loading
export const START_LOADING = 'START_LOADING'
export const END_LOADING = 'END_LOADING'